<?php

/**
 * Various utility functions for editor 
 *
 * @copyright   Copyright (C) 2020, Echo Plugins
 * @license http://opensource.org/licenses/gpl-2.0.php GNU Public License
 */
class EPKB_Editor_Utilities {
	
	public static $typography_defaults = [
		'font-family' => '',
		'font-size' => '',
		'font-size-units' => 'px',
		'font-weight' => '',
	];
	
	public static $google_fonts =  [
		"ABeeZee",
		"Abel",
		"Abhaya Libre",
		"Abril Fatface",
		"Aclonica",
		"Acme",
		"Actor",
		"Adamina",
		"Advent Pro",
		"Aguafina Script",
		"Akronim",
		"Aladin",
		"Alata",
		"Alatsi",
		"Aldrich",
		"Alef",
		"Alegreya Sans SC",
		"Alegreya Sans",
		"Alegreya SC",
		"Alegreya",
		"Aleo",
		"Alex Brush",
		"Alfa Slab One",
		"Alice",
		"Alike Angular",
		"Alike",
		"Allan",
		"Allerta Stencil",
		"Allerta",
		"Allura",
		"Almarai",
		"Almendra Display",
		"Almendra SC",
		"Almendra",
		"Amarante",
		"Amaranth",
		"Amatic SC",
		"Amethysta",
		"Amiko",
		"Amiri",
		"Amita",
		"Anaheim",
		"Andada",
		"Andika",
		"Angkor",
		"Annie Use Your Telescope",
		"Anonymous Pro",
		"Antic Didone",
		"Antic Slab",
		"Antic",
		"Anton",
		"Arapey",
		"Arbutus Slab",
		"Arbutus",
		"Architects Daughter",
		"Archivo Black",
		"Archivo Narrow",
		"Archivo",
		"Aref Ruqaa",
		"Arima Madurai",
		"Arimo",
		"Arizonia",
		"Armata",
		"Arsenal",
		"Artifika",
		"Arvo",
		"Arya",
		"Asap Condensed",
		"Asap",
		"Asar",
		"Asset",
		"Assistant",
		"Astloch",
		"Asul",
		"Athiti",
		"Atma",
		"Atomic Age",
		"Aubrey",
		"Audiowide",
		"Autour One",
		"Average Sans",
		"Average",
		"Averia Gruesa Libre",
		"Averia Libre",
		"Averia Sans Libre",
		"Averia Serif Libre",
		"B612 Mono",
		"B612",
		"Bad Script",
		"Bahiana",
		"Bahianita",
		"Bai Jamjuree",
		"Baloo 2",
		"Baloo Bhai 2",
		"Baloo Bhaina 2",
		"Baloo Chettan 2",
		"Baloo Da 2",
		"Baloo Paaji 2",
		"Baloo Tamma 2",
		"Baloo Tammudu 2",
		"Baloo Thambi 2",
		"Balsamiq Sans",
		"Balthazar",
		"Bangers",
		"Barlow Condensed",
		"Barlow Semi Condensed",
		"Barlow",
		"Barriecito",
		"Barrio",
		"Basic",
		"Baskervville",
		"Battambang",
		"Baumans",
		"Bayon",
		"Be Vietnam",
		"Bebas Neue",
		"Belgrano",
		"Bellefair",
		"Belleza",
		"Bellota Text",
		"Bellota",
		"BenchNine",
		"Bentham",
		"Berkshire Swash",
		"Beth Ellen",
		"Bevan",
		"Big Shoulders Display",
		"Big Shoulders Text",
		"Bigelow Rules",
		"Bigshot One",
		"Bilbo Swash Caps",
		"Bilbo",
		"BioRhyme Expanded",
		"BioRhyme",
		"Biryani",
		"Bitter",
		"Black And White Picture",
		"Black Han Sans",
		"Black Ops One",
		"Blinker",
		"Bokor",
		"Bonbon",
		"Boogaloo",
		"Bowlby One SC",
		"Bowlby One",
		"Brawler",
		"Bree Serif",
		"Bubblegum Sans",
		"Bubbler One",
		"Buda",
		"Buenard",
		"Bungee Hairline",
		"Bungee Inline",
		"Bungee Outline",
		"Bungee Shade",
		"Bungee",
		"Butcherman",
		"Butterfly Kids",
		"Cabin Condensed",
		"Cabin Sketch",
		"Cabin",
		"Caesar Dressing",
		"Cagliostro",
		"Cairo",
		"Caladea",
		"Calistoga",
		"Calligraffitti",
		"Cambay",
		"Cambo",
		"Candal",
		"Cantarell",
		"Cantata One",
		"Cantora One",
		"Capriola",
		"Cardo",
		"Carme",
		"Carrois Gothic SC",
		"Carrois Gothic",
		"Carter One",
		"Catamaran",
		"Caudex",
		"Caveat Brush",
		"Caveat",
		"Cedarville Cursive",
		"Ceviche One",
		"Chakra Petch",
		"Changa One",
		"Changa",
		"Chango",
		"Charm",
		"Charmonman",
		"Chathura",
		"Chau Philomene One",
		"Chela One",
		"Chelsea Market",
		"Chenla",
		"Cherry Cream Soda",
		"Cherry Swash",
		"Chewy",
		"Chicle",
		"Chilanka",
		"Chivo",
		"Chonburi",
		"Cinzel Decorative",
		"Cinzel",
		"Clicker Script",
		"Coda Caption",
		"Coda",
		"Codystar",
		"Coiny",
		"Combo",
		"Comfortaa",
		"Comic Neue",
		"Coming Soon",
		"Concert One",
		"Condiment",
		"Content",
		"Contrail One",
		"Convergence",
		"Cookie",
		"Copse",
		"Corben",
		"Cormorant Garamond",
		"Cormorant Infant",
		"Cormorant SC",
		"Cormorant Unicase",
		"Cormorant Upright",
		"Cormorant",
		"Courgette",
		"Courier Prime",
		"Cousine",
		"Coustard",
		"Covered By Your Grace",
		"Crafty Girls",
		"Creepster",
		"Crete Round",
		"Crimson Pro",
		"Crimson Text",
		"Croissant One",
		"Crushed",
		"Cuprum",
		"Cute Font",
		"Cutive Mono",
		"Cutive",
		"Damion",
		"Dancing Script",
		"Dangrek",
		"Darker Grotesque",
		"David Libre",
		"Dawning of a New Day",
		"Days One",
		"Dekko",
		"Delius Swash Caps",
		"Delius Unicase",
		"Delius",
		"Della Respira",
		"Denk One",
		"Devonshire",
		"Dhurjati",
		"Didact Gothic",
		"Diplomata SC",
		"Diplomata",
		"DM Mono",
		"DM Sans",
		"DM Serif Display",
		"DM Serif Text",
		"Do Hyeon",
		"Dokdo",
		"Domine",
		"Donegal One",
		"Doppio One",
		"Dorsa",
		"Dosis",
		"Dr Sugiyama",
		"Duru Sans",
		"Dynalight",
		"Eagle Lake",
		"East Sea Dokdo",
		"Eater",
		"EB Garamond",
		"Economica",
		"Eczar",
		"El Messiri",
		"Electrolize",
		"Elsie Swash Caps",
		"Elsie",
		"Emblema One",
		"Emilys Candy",
		"Encode Sans Condensed",
		"Encode Sans Expanded",
		"Encode Sans Semi Condensed",
		"Encode Sans Semi Expanded",
		"Encode Sans",
		"Engagement",
		"Englebert",
		"Enriqueta",
		"Epilogue",
		"Erica One",
		"Esteban",
		"Euphoria Script",
		"Ewert",
		"Exo 2",
		"Exo",
		"Expletus Sans",
		"Fahkwang",
		"Fanwood Text",
		"Farro",
		"Farsan",
		"Fascinate Inline",
		"Fascinate",
		"Faster One",
		"Fasthand",
		"Fauna One",
		"Faustina",
		"Federant",
		"Federo",
		"Felipa",
		"Fenix",
		"Finger Paint",
		"Fira Code",
		"Fira Mono",
		"Fira Sans Condensed",
		"Fira Sans Extra Condensed",
		"Fira Sans",
		"Fjalla One",
		"Fjord One",
		"Flamenco",
		"Flavors",
		"Fondamento",
		"Fontdiner Swanky",
		"Forum",
		"Francois One",
		"Frank Ruhl Libre",
		"Freckle Face",
		"Fredericka the Great",
		"Fredoka One",
		"Freehand",
		"Fresca",
		"Frijole",
		"Fruktur",
		"Fugaz One",
		"Gabriela",
		"Gaegu",
		"Gafata",
		"Galada",
		"Galdeano",
		"Galindo",
		"Gamja Flower",
		"Gayathri",
		"Gelasio",
		"Gentium Basic",
		"Gentium Book Basic",
		"Geo",
		"Geostar Fill",
		"Geostar",
		"Germania One",
		"GFS Didot",
		"GFS Neohellenic",
		"Gidugu",
		"Gilda Display",
		"Girassol",
		"Give You Glory",
		"Glass Antiqua",
		"Glegoo",
		"Gloria Hallelujah",
		"Goblin One",
		"Gochi Hand",
		"Gorditas",
		"Gothic A1",
		"Gotu",
		"Goudy Bookletter 1911",
		"Graduate",
		"Grand Hotel",
		"Gravitas One",
		"Great Vibes",
		"Grenze Gotisch",
		"Grenze",
		"Griffy",
		"Gruppo",
		"Gudea",
		"Gugi",
		"Gupter",
		"Gurajada",
		"Habibi",
		"Halant",
		"Hammersmith One",
		"Hanalei Fill",
		"Hanalei",
		"Handlee",
		"Hanuman",
		"Happy Monkey",
		"Harmattan",
		"Headland One",
		"Heebo",
		"Henny Penny",
		"Hepta Slab",
		"Herr Von Muellerhoff",
		"Hi Melody",
		"Hind Guntur",
		"Hind Madurai",
		"Hind Siliguri",
		"Hind Vadodara",
		"Hind",
		"Holtwood One SC",
		"Homemade Apple",
		"Homenaje",
		"Ibarra Real Nova",
		"IBM Plex Mono",
		"IBM Plex Sans Condensed",
		"IBM Plex Sans",
		"IBM Plex Serif",
		"Iceberg",
		"Iceland",
		"IM Fell Double Pica SC",
		"IM Fell Double Pica",
		"IM Fell DW Pica SC",
		"IM Fell DW Pica",
		"IM Fell English SC",
		"IM Fell English",
		"IM Fell French Canon SC",
		"IM Fell French Canon",
		"IM Fell Great Primer SC",
		"IM Fell Great Primer",
		"Imprima",
		"Inconsolata",
		"Inder",
		"Indie Flower",
		"Inika",
		"Inknut Antiqua",
		"Inria Sans",
		"Inria Serif",
		"Inter",
		"Irish Grover",
		"Istok Web",
		"Italiana",
		"Italianno",
		"Itim",
		"Jacques Francois Shadow",
		"Jacques Francois",
		"Jaldi",
		"Jim Nightshade",
		"Jockey One",
		"Jolly Lodger",
		"Jomhuria",
		"Jomolhari",
		"Josefin Sans",
		"Josefin Slab",
		"Jost",
		"Joti One",
		"Jua",
		"Judson",
		"Julee",
		"Julius Sans One",
		"Junge",
		"Jura",
		"Just Another Hand",
		"Just Me Again Down Here",
		"K2D",
		"Kadwa",
		"Kalam",
		"Kameron",
		"Kanit",
		"Kantumruy",
		"Karla",
		"Karma",
		"Katibeh",
		"Kaushan Script",
		"Kavivanar",
		"Kavoon",
		"Kdam Thmor",
		"Keania One",
		"Kelly Slab",
		"Kenia",
		"Khand",
		"Khmer",
		"Khula",
		"Kirang Haerang",
		"Kite One",
		"Knewave",
		"Kodchasan",
		"KoHo",
		"Kosugi Maru",
		"Kosugi",
		"Kotta One",
		"Koulen",
		"Kranky",
		"Kreon",
		"Kristi",
		"Krona One",
		"Krub",
		"Kulim Park",
		"Kumar One Outline",
		"Kumar One",
		"Kurale",
		"La Belle Aurore",
		"Lacquer",
		"Laila",
		"Lakki Reddy",
		"Lalezar",
		"Lancelot",
		"Lateef",
		"Lato",
		"League Script",
		"Leckerli One",
		"Ledger",
		"Lekton",
		"Lemon",
		"Lemonada",
		"Lexend Deca",
		"Lexend Exa",
		"Lexend Giga",
		"Lexend Mega",
		"Lexend Peta",
		"Lexend Tera",
		"Lexend Zetta",
		"Libre Barcode 128 Text",
		"Libre Barcode 128",
		"Libre Barcode 39 Extended Text",
		"Libre Barcode 39 Extended",
		"Libre Barcode 39 Text",
		"Libre Barcode 39",
		"Libre Baskerville",
		"Libre Caslon Display",
		"Libre Caslon Text",
		"Libre Franklin",
		"Life Savers",
		"Lilita One",
		"Lily Script One",
		"Limelight",
		"Linden Hill",
		"Literata",
		"Liu Jian Mao Cao",
		"Livvic",
		"Lobster Two",
		"Lobster",
		"Londrina Outline",
		"Londrina Shadow",
		"Londrina Sketch",
		"Londrina Solid",
		"Long Cang",
		"Lora",
		"Love Ya Like A Sister",
		"Loved by the King",
		"Lovers Quarrel",
		"Luckiest Guy",
		"Lusitana",
		"Lustria",
		"M PLUS 1p",
		"M PLUS Rounded 1c",
		"Ma Shan Zheng",
		"Macondo Swash Caps",
		"Macondo",
		"Mada",
		"Magra",
		"Maiden Orange",
		"Maitree",
		"Major Mono Display",
		"Mako",
		"Mali",
		"Mallanna",
		"Mandali",
		"Manjari",
		"Manrope",
		"Mansalva",
		"Manuale",
		"Marcellus SC",
		"Marcellus",
		"Marck Script",
		"Margarine",
		"Markazi Text",
		"Marko One",
		"Marmelad",
		"Martel Sans",
		"Martel",
		"Marvel",
		"Mate SC",
		"Mate",
		"Maven Pro",
		"McLaren",
		"Meddon",
		"MedievalSharp",
		"Medula One",
		"Meera Inimai",
		"Megrim",
		"Meie Script",
		"Merienda One",
		"Merienda",
		"Merriweather Sans",
		"Merriweather",
		"Metal Mania",
		"Metal",
		"Metamorphous",
		"Metrophobic",
		"Michroma",
		"Milonga",
		"Miltonian Tattoo",
		"Miltonian",
		"Mina",
		"Miniver",
		"Miriam Libre",
		"Mirza",
		"Miss Fajardose",
		"Mitr",
		"Modak",
		"Modern Antiqua",
		"Mogra",
		"Molengo",
		"Molle",
		"Monda",
		"Monofett",
		"Monoton",
		"Monsieur La Doulaise",
		"Montaga",
		"Montez",
		"Montserrat Alternates",
		"Montserrat Subrayada",
		"Montserrat",
		"Moul",
		"Moulpali",
		"Mountains of Christmas",
		"Mouse Memoirs",
		"Mr Bedfort",
		"Mr Dafoe",
		"Mr De Haviland",
		"Mrs Saint Delafield",
		"Mrs Sheppards",
		"Mukta Mahee",
		"Mukta Malar",
		"Mukta Vaani",
		"Mukta",
		"Mulish",
		"MuseoModerno",
		"Mystery Quest",
		"Nanum Brush Script",
		"Nanum Gothic Coding",
		"Nanum Gothic",
		"Nanum Myeongjo",
		"Nanum Pen Script",
		"Neucha",
		"Neuton",
		"New Rocker",
		"News Cycle",
		"Niconne",
		"Niramit",
		"Nixie One",
		"Nobile",
		"Nokora",
		"Norican",
		"Nosifer",
		"Notable",
		"Nothing You Could Do",
		"Noticia Text",
		"Noto Sans HK",
		"Noto Sans JP",
		"Noto Sans KR",
		"Noto Sans SC",
		"Noto Sans TC",
		"Noto Sans",
		"Noto Serif JP",
		"Noto Serif KR",
		"Noto Serif SC",
		"Noto Serif TC",
		"Noto Serif",
		"Nova Cut",
		"Nova Flat",
		"Nova Mono",
		"Nova Oval",
		"Nova Round",
		"Nova Script",
		"Nova Slim",
		"Nova Square",
		"NTR",
		"Numans",
		"Nunito Sans",
		"Nunito",
		"Odibee Sans",
		"Odor Mean Chey",
		"Offside",
		"Old Standard TT",
		"Oldenburg",
		"Oleo Script Swash Caps",
		"Oleo Script",
		"Open Sans",
		"Oranienbaum",
		"Orbitron",
		"Oregano",
		"Orienta",
		"Original Surfer",
		"Oswald",
		"Over the Rainbow",
		"Overlock SC",
		"Overlock",
		"Overpass Mono",
		"Overpass",
		"Ovo",
		"Oxanium",
		"Oxygen Mono",
		"Oxygen",
		"Pacifico",
		"Padauk",
		"Palanquin Dark",
		"Palanquin",
		"Pangolin",
		"Paprika",
		"Parisienne",
		"Passero One",
		"Passion One",
		"Pathway Gothic One",
		"Patrick Hand SC",
		"Patrick Hand",
		"Pattaya",
		"Patua One",
		"Pavanam",
		"Paytone One",
		"Peddana",
		"Peralta",
		"Permanent Marker",
		"Petit Formal Script",
		"Petrona",
		"Philosopher",
		"Piedra",
		"Pinyon Script",
		"Pirata One",
		"Plaster",
		"Play",
		"Playball",
		"Playfair Display SC",
		"Playfair Display",
		"Podkova",
		"Poiret One",
		"Poller One",
		"Poly",
		"Pompiere",
		"Pontano Sans",
		"Poor Story",
		"Poppins",
		"Port Lligat Sans",
		"Port Lligat Slab",
		"Pragati Narrow",
		"Prata",
		"Preahvihear",
		"Press Start 2P",
		"Pridi",
		"Princess Sofia",
		"Prociono",
		"Prompt",
		"Prosto One",
		"Proza Libre",
		"PT Mono",
		"PT Sans Caption",
		"PT Sans Narrow",
		"PT Sans",
		"PT Serif Caption",
		"PT Serif",
		"Public Sans",
		"Puritan",
		"Purple Purse",
		"Quando",
		"Quantico",
		"Quattrocento Sans",
		"Quattrocento",
		"Questrial",
		"Quicksand",
		"Quintessential",
		"Qwigley",
		"Racing Sans One",
		"Radley",
		"Rajdhani",
		"Rakkas",
		"Raleway Dots",
		"Raleway",
		"Ramabhadra",
		"Ramaraja",
		"Rambla",
		"Rammetto One",
		"Ranchers",
		"Rancho",
		"Ranga",
		"Rasa",
		"Rationale",
		"Ravi Prakash",
		"Recursive",
		"Red Hat Display",
		"Red Hat Text",
		"Red Rose",
		"Redressed",
		"Reem Kufi",
		"Reenie Beanie",
		"Revalia",
		"Rhodium Libre",
		"Ribeye Marrow",
		"Ribeye",
		"Righteous",
		"Risque",
		"Roboto Condensed",
		"Roboto Mono",
		"Roboto Slab",
		"Roboto",
		"Rochester",
		"Rock Salt",
		"Rokkitt",
		"Romanesco",
		"Ropa Sans",
		"Rosario",
		"Rosarivo",
		"Rouge Script",
		"Rowdies",
		"Rozha One",
		"Rubik Mono One",
		"Rubik",
		"Ruda",
		"Rufina",
		"Ruge Boogie",
		"Ruluko",
		"Rum Raisin",
		"Ruslan Display",
		"Russo One",
		"Ruthie",
		"Rye",
		"Sacramento",
		"Sahitya",
		"Sail",
		"Saira Condensed",
		"Saira Extra Condensed",
		"Saira Semi Condensed",
		"Saira Stencil One",
		"Saira",
		"Salsa",
		"Sanchez",
		"Sancreek",
		"Sansita",
		"Sarabun",
		"Sarala",
		"Sarina",
		"Sarpanch",
		"Satisfy",
		"Sawarabi Gothic",
		"Sawarabi Mincho",
		"Scada",
		"Scheherazade",
		"Schoolbell",
		"Scope One",
		"Seaweed Script",
		"Secular One",
		"Sedgwick Ave Display",
		"Sedgwick Ave",
		"Sen",
		"Sevillana",
		"Seymour One",
		"Shadows Into Light Two",
		"Shadows Into Light",
		"Shanti",
		"Share Tech Mono",
		"Share Tech",
		"Share",
		"Shojumaru",
		"Short Stack",
		"Shrikhand",
		"Siemreap",
		"Sigmar One",
		"Signika Negative",
		"Signika",
		"Simonetta",
		"Single Day",
		"Sintony",
		"Sirin Stencil",
		"Six Caps",
		"Skranji",
		"Slabo 13px",
		"Slabo 27px",
		"Slackey",
		"Smokum",
		"Smythe",
		"Sniglet",
		"Snippet",
		"Snowburst One",
		"Sofadi One",
		"Sofia",
		"Solway",
		"Song Myung",
		"Sonsie One",
		"Sora",
		"Sorts Mill Goudy",
		"Source Code Pro",
		"Source Sans Pro",
		"Source Serif Pro",
		"Space Mono",
		"Spartan",
		"Special Elite",
		"Spectral SC",
		"Spectral",
		"Spicy Rice",
		"Spinnaker",
		"Spirax",
		"Squada One",
		"Sree Krushnadevaraya",
		"Sriracha",
		"Srisakdi",
		"Staatliches",
		"Stalemate",
		"Stalinist One",
		"Stardos Stencil",
		"Stint Ultra Condensed",
		"Stint Ultra Expanded",
		"Stoke",
		"Strait",
		"Stylish",
		"Sue Ellen Francisco",
		"Suez One",
		"Sulphur Point",
		"Sumana",
		"Sunflower",
		"Sunshiney",
		"Supermercado One",
		"Sura",
		"Suranna",
		"Suravaram",
		"Suwannaphum",
		"Swanky and Moo Moo",
		"Syncopate",
		"Tajawal",
		"Tangerine",
		"Taprom",
		"Tauri",
		"Taviraj",
		"Teko",
		"Telex",
		"Tenali Ramakrishna",
		"Tenor Sans",
		"Text Me One",
		"Thasadith",
		"The Girl Next Door",
		"Tienne",
		"Tillana",
		"Timmana",
		"Tinos",
		"Titan One",
		"Titillium Web",
		"Tomorrow",
		"Trade Winds",
		"Trirong",
		"Trocchi",
		"Trochut",
		"Trykker",
		"Tulpen One",
		"Turret Road",
		"Ubuntu Condensed",
		"Ubuntu Mono",
		"Ubuntu",
		"Ultra",
		"Uncial Antiqua",
		"Underdog",
		"Unica One",
		"UnifrakturCook",
		"UnifrakturMaguntia",
		"Unkempt",
		"Unlock",
		"Unna",
		"Vampiro One",
		"Varela Round",
		"Varela",
		"Varta",
		"Vast Shadow",
		"Vesper Libre",
		"Viaoda Libre",
		"Vibes",
		"Vibur",
		"Vidaloka",
		"Viga",
		"Voces",
		"Volkhov",
		"Vollkorn SC",
		"Vollkorn",
		"Voltaire",
		"VT323",
		"Waiting for the Sunrise",
		"Wallpoet",
		"Walter Turncoat",
		"Warnes",
		"Wellfleet",
		"Wendy One",
		"Wire One",
		"Work Sans",
		"Yanone Kaffeesatz",
		"Yantramanav",
		"Yatra One",
		"Yellowtail",
		"Yeon Sung",
		"Yeseva One",
		"Yesteryear",
		"Yrsa",
		"ZCOOL KuaiLe",
		"ZCOOL QingKe HuangYou",
		"ZCOOL XiaoWei",
		"Zeyada",
		"Zhi Mang Xing",
		"Zilla Slab Highlight",
		"Zilla Slab",
	];
	
	public static function get_google_fonts_data() {
		
		$fonts = [];
		foreach ( self::$google_fonts as $font_name ) {
			$fonts[$font_name] = 'https://fonts.googleapis.com/css?family=' . str_replace( ' ', '+', $font_name ) . ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic';
		}
		
		return $fonts;
	}

	public static function sanitize_typography( $typography ) {

		$typography = is_array($typography) ? $typography : array();
		$typography = array_merge( EPKB_Editor_Utilities::$typography_defaults, $typography );

		$typography_filtered = [];
		$allowed_keys = array_keys( EPKB_Editor_Utilities::$typography_defaults );
		foreach ( $typography as $key => $value ) {

			if ( ! in_array( $key, $allowed_keys ) ) {
				continue;
			}

			$typography_filtered[$key] = sanitize_text_field( $value );
		}

		return $typography_filtered;
	}

	/**
	 * @param $kb_config
	 * @param string $main_page_zone_name
	 * @param string $article_page_zone_name
	 * @param string $archive_page_zone_name
	 * @return array
	 */
	public static function get_editor_urls( $kb_config, $main_page_zone_name='settings', $article_page_zone_name='settings', $archive_page_zone_name='settings' ) {

		$main_url = EPKB_KB_Handler::get_first_kb_main_page_url( $kb_config );
		$main_url = empty($main_url) ? '' : add_query_arg( array('preopen' => $main_page_zone_name, 'action' => 'epkb_load_editor'), $main_url );

		$article_url = EPKB_KB_Handler::get_first_kb_article_url( $kb_config );
		$article_url = empty($article_url) ? '' : add_query_arg( array('preopen' => $article_page_zone_name, 'action' => 'epkb_load_editor'), $article_url );

		$archive_url = EPKB_KB_Handler::get_kb_category_with_most_articles_url( $kb_config );
		$archive_url = empty($archive_url) ? '' : add_query_arg( array('preopen' => $archive_page_zone_name, 'action' => 'epkb_load_editor'), $archive_url );

		return [
			'main_page_url' => $main_url,
			'article_page_url' => $article_url,
			'archive_url' => $archive_url ];
	}

	/**
	 * @param $page_type
	 * @param $zone_name
	 * @return array|mixed|string
	 */
	public static function get_one_editor_url( $page_type, $zone_name='settings' ) {
		$kb_config = epkb_get_instance()->kb_config_obj->get_current_kb_configuration();
		if ( is_wp_error( $kb_config ) ) {
			return '';
		}

		$url = '';
		if ( $page_type == 'main_page' ) {
			$url = self::get_editor_urls( $kb_config, $zone_name );
			$url = $url['main_page_url'];

		} else if ( $page_type == 'article_page' ) {
			$url = self::get_editor_urls( $kb_config, 'settings',$zone_name );
			$url = $url['article_page_url'];

		} else if ( $page_type == 'archive_page' ) {
			$url = self::get_editor_urls( $kb_config, 'settings', 'settings', $zone_name );
			$url = $url['archive_url'];
		}

		return $url;
	}
}